// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: queue/queue_service.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_queue_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_queue_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_queue_service_proto_rawDescGZIP(), []int{0}
}

func (x *JoinQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket *Ticket `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *JoinQueueResponse) Reset() {
	*x = JoinQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_queue_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueResponse) ProtoMessage() {}

func (x *JoinQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_queue_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueResponse.ProtoReflect.Descriptor instead.
func (*JoinQueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_queue_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinQueueResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type RetrieveNextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetrieveNextRequest) Reset() {
	*x = RetrieveNextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_queue_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveNextRequest) ProtoMessage() {}

func (x *RetrieveNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_queue_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveNextRequest.ProtoReflect.Descriptor instead.
func (*RetrieveNextRequest) Descriptor() ([]byte, []int) {
	return file_queue_queue_service_proto_rawDescGZIP(), []int{2}
}

type RetrieveNextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket *Ticket `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *RetrieveNextResponse) Reset() {
	*x = RetrieveNextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_queue_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveNextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveNextResponse) ProtoMessage() {}

func (x *RetrieveNextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_queue_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveNextResponse.ProtoReflect.Descriptor instead.
func (*RetrieveNextResponse) Descriptor() ([]byte, []int) {
	return file_queue_queue_service_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveNextResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type GetUpcomingTicketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quantity int64 `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *GetUpcomingTicketsRequest) Reset() {
	*x = GetUpcomingTicketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_queue_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUpcomingTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingTicketsRequest) ProtoMessage() {}

func (x *GetUpcomingTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_queue_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingTicketsRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingTicketsRequest) Descriptor() ([]byte, []int) {
	return file_queue_queue_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpcomingTicketsRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetUpcomingTicketsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tickets []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
}

func (x *GetUpcomingTicketsResponse) Reset() {
	*x = GetUpcomingTicketsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queue_queue_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUpcomingTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingTicketsResponse) ProtoMessage() {}

func (x *GetUpcomingTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_queue_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingTicketsResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingTicketsResponse) Descriptor() ([]byte, []int) {
	return file_queue_queue_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUpcomingTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

var File_queue_queue_service_proto protoreflect.FileDescriptor

var file_queue_queue_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x1a, 0x19, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a,
	0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x11, 0x4a, 0x6f,
	0x69, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a,
	0x14, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x37, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x45, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x55, 0x70, 0x63, 0x6f,
	0x6d, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x32, 0xf8, 0x01, 0x0a,
	0x0c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x17, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4e, 0x65, 0x78, 0x74, 0x12,
	0x1a, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x4e, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x12, 0x20, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70, 0x63, 0x6f,
	0x6d, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x70,
	0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queue_queue_service_proto_rawDescOnce sync.Once
	file_queue_queue_service_proto_rawDescData = file_queue_queue_service_proto_rawDesc
)

func file_queue_queue_service_proto_rawDescGZIP() []byte {
	file_queue_queue_service_proto_rawDescOnce.Do(func() {
		file_queue_queue_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_queue_queue_service_proto_rawDescData)
	})
	return file_queue_queue_service_proto_rawDescData
}

var file_queue_queue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_queue_queue_service_proto_goTypes = []interface{}{
	(*JoinQueueRequest)(nil),           // 0: queue.JoinQueueRequest
	(*JoinQueueResponse)(nil),          // 1: queue.JoinQueueResponse
	(*RetrieveNextRequest)(nil),        // 2: queue.RetrieveNextRequest
	(*RetrieveNextResponse)(nil),       // 3: queue.RetrieveNextResponse
	(*GetUpcomingTicketsRequest)(nil),  // 4: queue.GetUpcomingTicketsRequest
	(*GetUpcomingTicketsResponse)(nil), // 5: queue.GetUpcomingTicketsResponse
	(*Ticket)(nil),                     // 6: queue.Ticket
}
var file_queue_queue_service_proto_depIdxs = []int32{
	6, // 0: queue.JoinQueueResponse.ticket:type_name -> queue.Ticket
	6, // 1: queue.RetrieveNextResponse.ticket:type_name -> queue.Ticket
	6, // 2: queue.GetUpcomingTicketsResponse.tickets:type_name -> queue.Ticket
	0, // 3: queue.QueueService.JoinQueue:input_type -> queue.JoinQueueRequest
	2, // 4: queue.QueueService.RetrieveNext:input_type -> queue.RetrieveNextRequest
	4, // 5: queue.QueueService.GetUpcomingTickets:input_type -> queue.GetUpcomingTicketsRequest
	1, // 6: queue.QueueService.JoinQueue:output_type -> queue.JoinQueueResponse
	3, // 7: queue.QueueService.RetrieveNext:output_type -> queue.RetrieveNextResponse
	5, // 8: queue.QueueService.GetUpcomingTickets:output_type -> queue.GetUpcomingTicketsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_queue_queue_service_proto_init() }
func file_queue_queue_service_proto_init() {
	if File_queue_queue_service_proto != nil {
		return
	}
	file_queue_queue_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_queue_queue_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_queue_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_queue_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveNextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_queue_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveNextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_queue_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUpcomingTicketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queue_queue_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUpcomingTicketsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queue_queue_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_queue_service_proto_goTypes,
		DependencyIndexes: file_queue_queue_service_proto_depIdxs,
		MessageInfos:      file_queue_queue_service_proto_msgTypes,
	}.Build()
	File_queue_queue_service_proto = out.File
	file_queue_queue_service_proto_rawDesc = nil
	file_queue_queue_service_proto_goTypes = nil
	file_queue_queue_service_proto_depIdxs = nil
}
