# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.queue import queue_service_pb2 as queue_dot_queue__service__pb2


class QueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinQueue = channel.unary_unary(
                '/queue.QueueService/JoinQueue',
                request_serializer=queue_dot_queue__service__pb2.JoinQueueRequest.SerializeToString,
                response_deserializer=queue_dot_queue__service__pb2.JoinQueueResponse.FromString,
                )
        self.RetrieveNext = channel.unary_unary(
                '/queue.QueueService/RetrieveNext',
                request_serializer=queue_dot_queue__service__pb2.RetrieveNextRequest.SerializeToString,
                response_deserializer=queue_dot_queue__service__pb2.RetrieveNextResponse.FromString,
                )
        self.GetUpcomingTickets = channel.unary_unary(
                '/queue.QueueService/GetUpcomingTickets',
                request_serializer=queue_dot_queue__service__pb2.GetUpcomingTicketsRequest.SerializeToString,
                response_deserializer=queue_dot_queue__service__pb2.GetUpcomingTicketsResponse.FromString,
                )


class QueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpcomingTickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinQueue,
                    request_deserializer=queue_dot_queue__service__pb2.JoinQueueRequest.FromString,
                    response_serializer=queue_dot_queue__service__pb2.JoinQueueResponse.SerializeToString,
            ),
            'RetrieveNext': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveNext,
                    request_deserializer=queue_dot_queue__service__pb2.RetrieveNextRequest.FromString,
                    response_serializer=queue_dot_queue__service__pb2.RetrieveNextResponse.SerializeToString,
            ),
            'GetUpcomingTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpcomingTickets,
                    request_deserializer=queue_dot_queue__service__pb2.GetUpcomingTicketsRequest.FromString,
                    response_serializer=queue_dot_queue__service__pb2.GetUpcomingTicketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queue.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/queue.QueueService/JoinQueue',
            queue_dot_queue__service__pb2.JoinQueueRequest.SerializeToString,
            queue_dot_queue__service__pb2.JoinQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/queue.QueueService/RetrieveNext',
            queue_dot_queue__service__pb2.RetrieveNextRequest.SerializeToString,
            queue_dot_queue__service__pb2.RetrieveNextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUpcomingTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/queue.QueueService/GetUpcomingTickets',
            queue_dot_queue__service__pb2.GetUpcomingTicketsRequest.SerializeToString,
            queue_dot_queue__service__pb2.GetUpcomingTicketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
