# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue/queue_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from queue import queue_message_pb2 as queue_dot_queue__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19queue/queue_service.proto\x12\x05queue\x1a\x19queue/queue_message.proto\"#\n\x10JoinQueueRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x11JoinQueueResponse\x12\x1d\n\x06ticket\x18\x01 \x01(\x0b\x32\r.queue.Ticket\"\x15\n\x13RetrieveNextRequest\"5\n\x14RetrieveNextResponse\x12\x1d\n\x06ticket\x18\x01 \x01(\x0b\x32\r.queue.Ticket\"-\n\x19GetUpcomingTicketsRequest\x12\x10\n\x08quantity\x18\x01 \x01(\x03\"<\n\x1aGetUpcomingTicketsResponse\x12\x1e\n\x07tickets\x18\x01 \x03(\x0b\x32\r.queue.Ticket2\xf8\x01\n\x0cQueueService\x12@\n\tJoinQueue\x12\x17.queue.JoinQueueRequest\x1a\x18.queue.JoinQueueResponse\"\x00\x12I\n\x0cRetrieveNext\x12\x1a.queue.RetrieveNextRequest\x1a\x1b.queue.RetrieveNextResponse\"\x00\x12[\n\x12GetUpcomingTickets\x12 .queue.GetUpcomingTicketsRequest\x1a!.queue.GetUpcomingTicketsResponse\"\x00\x42\x14Z\x12/proto_files/queueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue.queue_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022/proto_files/queue'
  _globals['_JOINQUEUEREQUEST']._serialized_start=63
  _globals['_JOINQUEUEREQUEST']._serialized_end=98
  _globals['_JOINQUEUERESPONSE']._serialized_start=100
  _globals['_JOINQUEUERESPONSE']._serialized_end=150
  _globals['_RETRIEVENEXTREQUEST']._serialized_start=152
  _globals['_RETRIEVENEXTREQUEST']._serialized_end=173
  _globals['_RETRIEVENEXTRESPONSE']._serialized_start=175
  _globals['_RETRIEVENEXTRESPONSE']._serialized_end=228
  _globals['_GETUPCOMINGTICKETSREQUEST']._serialized_start=230
  _globals['_GETUPCOMINGTICKETSREQUEST']._serialized_end=275
  _globals['_GETUPCOMINGTICKETSRESPONSE']._serialized_start=277
  _globals['_GETUPCOMINGTICKETSRESPONSE']._serialized_end=337
  _globals['_QUEUESERVICE']._serialized_start=340
  _globals['_QUEUESERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
